### PR TITLE
fix(model.get()): handle null when entity does not exist

### PR DESCRIPTION
**Pull request by mickdekkers**
I was getting the same error described in #26, except with `null` instead of `undefined`:

```
Cannot read property 'Symbol(KEY)' of null
```

Adding `|| data[0] === null` to the `if` condition fixed the issue for me 🙂

### CODE REVIEW

**Comment by sebelga** [comment]
Hello!
Thanks for the PR. Before adding the patch it'd be interesting to understand in which cases a null value is returned. Is it with Dataloader? Do you have more details on where it fails? 
I'd like to add integration tests for the scenario when we have one.
Cheers!

**Comment by mickdekkers** [comment]
Hi @sebelga,

In my specific case it occurred with both a dataloader and a transaction.
I haven't tried to reproduce it with different configuration yet.

Basically:

```
model.get(
    id,
    undefined,
    undefined,
    transaction,
    {
      dataloader,
    },
);
```

I'll try to provide some more detail soon, but it might be a couple days 🙂

**Comment by sebelga** [comment]
Great, thanks for the update. I'm away a few days but we'll get to it asap 👍

**Comment by mickdekkers** [comment]
A quick update: I tried to make a minimum reproduction repo, but have so far been unable to reproduce the issue.

Last week, I made a temporary fork of gstore-node with this PR merged and pointed our project's package.json to that. This did fix the issue for us, but contributing the fix with tests to this repo would be much better of course.

I'll most likely have to really dig in to our project to find out what about our particular setup is causing the issue, but I'm afraid I won't be able to spend enough time to do this in the near future. I also can't share the project code since it's proprietary.

In the meantime, I've uploaded the (WIP) reproduction repo [here](https://github.com/mickdekkers/gstore-node-symbol-key-null-error-repro). Note: this does not reproduce the issue yet. It throws a `not found` error, as one would expect.

**Comment by sebelga** [comment]
Hello,
Thanks for looking into it. I will try to reproduce it in an integration test on my side as soon as I have some time ahead 😊 At first sight, it seems like your fix should not break anything but I prefer to have a look into it before merging.

**Comment by mickdekkers** [comment]
Great, thanks for merging! 😄

**Pull request merged**
