### PR TITLE
Update @google-cloud/datastore to v4

### PR DESCRIPTION
**Pull request by vzts**
resolve https://github.com/sebelga/gstore-node/issues/166

### CODE REVIEW

**Comment by sebelga** [comment]
Hi, just a quick message to let you know that I don't forget this PR. I am just going through something and can't dedicate time on gstore-node right now. 
I will get back to it as soon as I can, thanks for your patience!

**Comment by btorresgil** [comment]
Should the @google-cloud/datastore library be a peer dependency instead of dependency?  Since we have to access it directly during `gstore.connect()`?  I'm new to gstore-node, so forgive me if this suggestion doesn't make sense.

**Comment by lesmo** [comment]
> Should the @google-cloud/datastore library be a peer dependency instead of dependency? Since we have to access it directly during `gstore.connect()`? I'm new to gstore-node, so forgive me if this suggestion doesn't make sense.

I'm also new but as i'm getting a hold of all the nuts and bolts of it, I believe that it makes total sense. That would relieve this package from keeping up with minor releases of the Datastore one.

**Comment by sebelga** [comment]
Sorry guys, moving house, changing country, loads of things to deal with 😊 
I also think it does make sense to have it as a peer dependency. I just need to have a second look and try to remember why I didn't do it in the first place. Cheers!

**Comment by codmajik** [comment]
Hi @sebelga, any feedback on this?

**Comment by sebelga** [comment]
Hi, sorry for the super late answer. Yes I will look into it this next few days and get it merged 😊

**Comment by sebelga** [comment]
@btorresgil You are right, it is better to declare `@google-cloud/datastore` as a peer dependency. Thanks for the input! 👍 
I created a PR (https://github.com/sebelga/gstore-node/pull/177) for it, it will be a breaking change but I think necessary.
I will close this PR as the other solves the problem. Thanks for the patience!

**Pull request closed without merging**
