### PR TITLE
Added virtual properties for all fields defined in the schema

### PR DESCRIPTION
**Pull request by jfbenckhuijsen**
I've added some logic to create virtual properties for each of the fields in the schema. This way I can access properties directly via MyModel.myProperty instead of MyModel.entityData.myProperty, same as can be done in Mongoose

### CODE REVIEW

**Comment by sebelga** [comment]
It's interesting. Although I don't think we could use it just like this in gstore because properties from the Schema could override internal properties of the Model. I just made a test and I could override "constructor", "gstore", and also a custom method that I had on the Schema (ex: userSchema.method('verifyPassword', verifyPassword)).

Do you know if Mongoose define a set of **reserved property names** that can not be used for the Models definition?

**Comment by jfbenckhuijsen** [comment]
As for keywords override internal fields, looks like Mongoose also has this issue and has defined some reserved keywords. See http://mongoosejs.com/docs/api.html#schema_Schema.reserved

As for properties overriding custom methods: from a design point of view, it would be very strange to define an object (looking at Models in an object oriented way) having a property and a function with the same name. So I think that should be the developers responsibility to keep them separated (i.e. having both a birthday property and a birthday method om the same object would be strange).

Concerning this patch: I can imagine adding a test to verify whether property overrides one of the reserved words for GStore-node and throw an error in that case. To preserve backwards compatibility we can add an option to the schema or model to enable this functionality an the reserved word checking. Not sure if preserving this kind of backwards compatibility is a hot issue for you.

**Comment by sebelga** [comment]
Actually I forgot but the same behaviour of *reserved* was copied from Mongoose (https://github.com/sebelga/gstore-node/blob/master/lib/schema.js#L175). :) So yeah we could add a few more properties on that hashtable ("gstore", "entityData", "constructor" and any other we might think of).

Also could you add some tests and update the README.md? I think the documentation could go under Entity -> Properties. Mention that virtual properties are automatically added and mapped from entityData. (they can both be accessed and set) + a short code sample?

I think we can safely add this new feature and not worry too much about those few new reserved properties that might break some projects. I think it shouldn't affect almost anyone (I hope!). I am in the middle of adding #11 (Promises) where there will be more concern about some breaking change. ;)

**Comment by jfbenckhuijsen** [comment]
Will do, I'll be at a conference in the coming days, so that'll be next week before I can add them.

**Comment by sebelga** [comment]
Great, no hurry at all. thank you!

**Comment by sebelga** [comment]
Great stuff! I think you can safely delete the test you added at line 106 as it is covered by the one on L302. Also could you squash this in 1 commit. I know I haven't been doing this much (at all) but from now on I'd like to squash features/fixes from branches in 1 commit before merging to dev. :) thanks!

**Comment by jfbenckhuijsen** [comment]
Squash -> NP, was still working on it a bit.
Test -> Your call, I personally like my test small and focussed on testing individual stuff, but thats just a matter of taste ;-)

**Comment by jfbenckhuijsen** [comment]
Test is removed. Squashing will be an issue: I had a merge of your master in between commits, messing up the squashing. Will take that into account for other changes, but won't work for now.

**Pull request merged**
