### PR TITLE
Initial setup of method to query model objects

### LINKED ISSUE #22: Preferred way to transform a query result back to an entity
As far as I can see now, results from a query are the raw results from the query executed by the underlying gcloud-node library? What would be the preferred way to convert these entities back to gstore-node Model objects?

I.e my use case is the following roughly:
``
query(..., (entities) => {
  // do something with entities, update some properties
  entity.save();
});
``

### PR DESCRIPTION
**Pull request by jfbenckhuijsen**
Initial setup for a method to query model objects (entities) instead of plain objects. Not complete yet, just an initial setup to discuss API.

Fixes #22 once pull accepted.

### CODE REVIEW

**Comment by sebelga** [comment]
I was more thinking to add a property to the query.run() "options" parameter object (which I just realised is not documented!). Something like: { responseFormat: 'model' }. (So we leave the door opened for maybe other types in the future.)  
Then in the response handler if the format is 'model' have a utility function doing the map stuff. So we can use this same behaviour for the list() and findAround() function. Passing the same "responseFormat" option. What do you think?

**Comment by jfbenckhuijsen** [comment]
Hmm, I'm generally not happy with passing options to a method to realise some other behaviour by a method. Mainly for the reason you stated yourself: you need to check the docs to see this behaviour exists, whereas a method makes the existence directly clear from the interface (i.e. following Robert Martin's Clean Code book here). 

Having the same behaviour across multiple functions (list9), findAround()) of course is an argument in favour of passing around options parameters. However, I would then also expect the same for e.g. findOne (especially findOne(), as the result is a single object I might want to update). The current API doesn't allow passing in some set of options to findOne(). 

The API of findAround() and list() does have settings of course. For list(), the set of options is closely related to the query and it's result, whereas for findAround() to me this is less the case, as the API is just the before/after setting.

My 2c.. Let me know what you think. In the mean time, I'll rebase the branch, sigh... ;-)

**Comment by sebelga** [comment]
I see what you mean by not doing too many things passing options. I still think that in this case we would just be asking for a different response format and not to actually perform new logic.
I am not against having a "shortcut" on the API to do queries that return models (modelQuery()) but internally it should call query() with a parameter so we don't duplicate the same function code twice just to change the response format.

So for example modelQuery could do something like

```js
const args = Array.prototype.slice(arguments);
args.push({ responseFormat: 'model' });
return this.query.apply(this, args);
```
Then the options object inside query.run() should extend this new parent options parameter.

Just trying to avoid duplicate code here but if you come up with a better idea happy to hear :)

findOne() like get() already returns an entity model so we don't have to worry about those.

**Comment by sebelga** [comment]
Hi, was busy on a project and now coming back to gstore :) Do you want me to continue with this feature?

**Pull request closed without merging**
